name: Build and Deploy via SMB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Disable ESLint CI Strict Mode
        run: echo "DISABLE_ESLINT_PLUGIN=true" >> $GITHUB_ENV

      - name: Build Project
        run: |
          export CI=false
          npm run build

      - name: Create build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ragbot-build
          path: |
            ${{ github.workspace }}/build

      - name: Create Server Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ragbot-server
          path: |
            ${{ github.workspace }}/server/server.js

  deploy:
    needs: build
    runs-on: [self-hosted, midtest_frontend]
    steps:
      - name: Download build to middleware
        uses: actions/download-artifact@v4
        with:
          name: ragbot-build
          path: C:\MID_TRANSFER\React\retrieval-augmented-chatbot-webapp\build

      - name: Download server to middleware
        uses: actions/download-artifact@v4
        with:
          name: ragbot-server
          path: C:\MID_TRANSFER\React\retrieval-augmented-chatbot-webapp\server
