name: Build and Deploy via SMB

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Disable ESLint CI Strict Mode
        run: echo "DISABLE_ESLINT_PLUGIN=true" >> $GITHUB_ENV

      - name: Build Project
        run: |
          export CI=false
          npm run build

      - name: Debug SMB Connectivity
        run: |
          echo "Checking network connectivity..."
          ping -c 4 172.21.56.34
          
          echo "Checking if SMB port 445 is open..."
          nc -zv 172.21.56.34 445 || echo "Port 445 is not accessible!"

      - name: Copy Build Folder via SMB
        run: |
          sudo mount -t cifs //172.21.56.34/MID_RAGBOT /mnt \
            -o username=${{ secrets.DEPLOY_USER }},password=${{ secrets.DEPLOY_PASSWORD }},vers=2.1
          
          sudo cp -r build/* /mnt/build/
          sudo umount /mnt

