name: Build and Deploy to Middleware Server

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - midprod_frontend
          - midtest_frontend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: |
          npm test -- --watchAll=false --ci

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: |
          export CI=false
          npm run build

      - name: Create Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ragbot-build
          path: |
            ${{ github.workspace }}/build

      - name: Create Server Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ragbot-server
          path: |
            ${{ github.workspace }}/server

      - name: Create Port Configuration Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ragbot-portconfiguration
          path: |
            ${{ github.workspace }}/src/portConfigurtion.js

  deploy:
    needs: build
    runs-on: ${{ inputs.environment == 'midprod_frontend' && 'self-hosted' ||
      inputs.environment == 'midtest_frontend' && 'self-hosted' }}
    steps:
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: ragbot-build
          path: C:\middleware\MID_AI\build

      - name: Download port configuration file
        uses: actions/download-artifact@v4
        with:
          name: ragbot-portconfiguration
          path: C:\middleware\MID_AI\src

      - name: Download backend server files
        uses: actions/download-artifact@v4
        with:
          name: ragbot-server
          path: C:\middleware\MID_AI\server

      - name: Install Server Dependencies
        run: |
          cd C:\middleware\MID_AI\server
          npm install

      - name: Deploy to IIS
        shell: powershell
        run: |
          $websiteName = "mid_ai-bot"
          $iisPath = "IIS:\Sites\$websiteName"
          $buildPath = "C:\middleware\MID_AI\build"
          $httpsPort = 3448
          $certStoreLocation = "Cert:\LocalMachine\My"
          $certificateThumbprint = "5A89675513DE81A903ABA94A904F48F3941F661C"


          # Ensure the directories exist
          New-Item -ItemType Directory -Path $buildPath -Force | Out-Null
          New-Item -ItemType Directory -Path "C:\middleware\MID_AI\src" -Force | Out-Null
          New-Item -ItemType Directory -Path "C:\middleware\MID_AI\server" -Force | Out-Null

          # Check if the IIS site exists
          if (Get-Website -Name $websiteName -ErrorAction SilentlyContinue) {
              Write-Output "Website $websiteName exists. Updating..."
              Stop-Website -Name $websiteName
          } else {
              Write-Output "Creating new website $websiteName..."
              New-Website -Name $websiteName -PhysicalPath $buildPath -Port 3449 -CertStoreLocation $certStoreLocation -Protocol https
          }

          # Restart IIS site
          Start-Website -Name $websiteName
          Write-Output "Deployment complete!"
