name: Build and Deploy via PowerShell Remoting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: 🔎 Check IP
        run: curl https://api.ipify.org

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Disable ESLint CI Strict Mode
        run: echo "DISABLE_ESLINT_PLUGIN=true" >> $GITHUB_ENV

      - name: Build Project
        run: |
          npm run build

      - name: Deploy to Windows Server using PowerShell Remoting
        shell: pwsh
        run: |
          $secpasswd = ConvertTo-SecureString "${{ secrets.DEPLOY_PASSWORD }}" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ("${{ secrets.DEPLOY_USER }}", $secpasswd)
          
          Invoke-Command -ComputerName "${{ secrets.DEPLOY_HOST }}" -Credential $credential -ScriptBlock {
            param ($deployPath)

            Write-Host "Ensuring target directory exists..."
            New-Item -ItemType Directory -Path $deployPath -Force | Out-Null

            Write-Host "Copying build files..."
            Copy-Item -Path "$env:GITHUB_WORKSPACE\build\*" -Destination "$deployPath\build" -Recurse -Force

            Write-Host "Restarting IIS to apply changes..."
            iisreset
          } -ArgumentList "${{ secrets.DEPLOY_PATH }}"
