name: Build and Deploy to Middleware Server

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: |
          npm test -- --watchAll=false --ci

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: |
          export CI=false
          npm run build

      - name: Create Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ragbot-build
          path: |
            ${{ github.workspace }}/build

      - name: Create Server Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ragbot-server
          path: |
            ${{ github.workspace }}/server

      - name: Create Port Configuration Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ragbot-portconfiguration
          path: |
            ${{ github.workspace }}/src/portConfigurtion.js

  deploy:
    needs: build
    runs-on: [self-hosted, midtest_frontend]
    steps:
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: ragbot-build
          path: C:\MID_TRANSFER\React\retrieval-augmented-chatbot-webapp\build

      - name: Download Server
        uses: actions/download-artifact@v4
        with:
          name: ragbot-server
          path: C:\MID_TRANSFER\React\retrieval-augmented-chatbot-webapp\server

      - name: Download Port Configuration
        uses: actions/download-artifact@v4
        with:
          name: ragbot-portconfiguration
          path: C:\MID_TRANSFER\React\retrieval-augmented-chatbot-webapp\src